### ISSUE TITLE
Many errors when no user groups and no resource groups exists

### ISSUE THREAD

**Issue by sashabeep** [BBloke/evo-migrate#2]
Test: evo 2.0.4 php 7.4/8.1 - no difference

I've already wiped all the admin users except single one and i have no documents/user groups and there is no web users too on my site. I cannot get all the process done. Getting a lot of SQL errors without any result. I even tried to create a document group and resources group and put a couple resources but it still doesnt work. 

```« Evolution CMS Parse Error »
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'membergroup' in 'field list'
```

```EvolutionCMS\Database->query(string $var1)
assets/modules/evomigrate/evomigrate.module.inc.php on line 218
```

I tried to comment everything about user groups in script and it still doesnt work

**Comment by BBloke** [comment]
Hi,

I removed the SQL from the main branch and I've just published a new release.  The error is due to not being able to recreate the user/resource links for v1/v2 web users for v3.

You will have to start the migration from scratch (restore DB).  The migration should complete correctly.  You will have to recreate and user/resource links for "web" content which represents the webusers of old.

**Comment by sashabeep** [comment]
Still no effect.

```
« Evolution CMS Parse Error »
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'member' in 'where clause'

....
AgelxNash\Modx\Evo\Database\AbstractDatabase->delete(string $var1, 'WHERE member=1')
assets/modules/evomigrate/evomigrate.module.inc.php on line 215
```

**Comment by BBloke** [comment]
If you are happy for me to have a look, you are welcome to email me at bbloke at blueyonder.co.uk

**Comment by BBloke** [comment]
I'm not quite sure that error is really on the migrate script.  The script doesn't make use of anything v3 derived.

**Comment by Bahbv** [comment]
I'm experiencing the same problem trying to upgrade from 2.0.4. Using the updater script in v1.0.10 

"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'membergroup' in 'field list'"

**Comment by BBloke** [comment]
@Bahbv I'm happy to take a look at things if you wish to email me some details.  Email address a couple of posts above.  

The only thing I can see at the moment is at the very beginning before anything happens.

**Comment by Bahbv** [comment]
Hi BBloke, thanks for the offer but this was a customers live site which I'm not allowed to give you access to.

I could send you the 2.0.4 database if you want.

Anyhow, I managed to update the site by commenting out the following lines in your script
Line 290 ` $rs = $modx->db->query($sql);`
Line 298 `$modx->db->delete($modx->getFullTableName('user_settings'), "member=".$oldId);`
Line 299 `$modx->db->delete($modx->getFullTableName('member_groups'), "member=".$oldId);`

I wasn't using any webusers but your script is the easiest way to upgrade to CE 3.x.x

Thanks!

**Comment by BBloke** [comment]
I was thinking that it could be when a site has no users or permissions.

I'll try and find some time to do a fresh install of v1 and v2 and migrate without users to see what happens.

**Comment by Bahbv** [comment]
Some additional info that might help;

- I haven't had any issues with updating from the latest 1.4.x with only
regular administrator users.
- This 2.0.4 install indeed only had normal administrator users and no
webusers/perms.

None of our sites use webusers but, since CE 3.1.x is the only version
running smooth on PHP 8 for me is why I am using your script.

Thanks for making it!

Op di 6 dec. 2022 11:09 schreef BBloke ***@***.***>:

**Comment by BBloke** [comment]
I've installed a fresh v1.4 and ran the migrate script without issue.

I'm having trouble installing a fresh v2 on php8.0 or even installing v1.4 and migrating to v2 in order to test things in v2.

There must be something different between my own site, a fresh install and the sites where you are getting errors!

I'll persist on trying to get a v2 site up and running so I can test to see what is happening.

**Comment by BBloke** [comment]
FInally.  Figured out my error on installing v2.  As v2 uses the core there seems to be more going on with checks hence the errors.

I'm testing things on v2 fresh install at the moment.  I will test on my own sample site with users/permissions in v1.4 and see what happens. 

If all goes well, I'll update the code!

**Comment by BBloke** [comment]
New code coming to correct these issues.

**Comment by sashabeep** [comment]
@BBloke test site on 2.0.4 completely broken after installation via zip upload or from extras

```
<b>Fatal error</b>:  Uncaught TypeError: ReflectionProperty::getValue(): Argument #1 ($object) must be of type ?object, string given in /home/.../core/vendor/agelxnash/modx-evo-database/src/Drivers/IlluminateDriver.php:62
Stack trace:
#0 /home/.../core/vendor/agelxnash/modx-evo-database/src/Drivers/IlluminateDriver.php(62): ReflectionProperty-&gt;getValue('Illuminate\\Data...')
#1 /home/.../core/vendor/agelxnash/modx-evo-database/src/AbstractDatabase.php(295): AgelxNash\Modx\Evo\Database\Drivers\IlluminateDriver-&gt;__construct(Array)
#2 /home/.../core/vendor/agelxnash/modx-evo-database/src/Database.php(13): AgelxNash\Modx\Evo\Database\AbstractDatabase-&gt;setDriver('AgelxNash\\Modx\\...')
#3 /home/.../core/src/Database.php(14): AgelxNash\Modx\Evo\Database\Database-&gt;__construct(Array, 'AgelxNash\\Modx\\...')
#4 /home/.../core/src/Providers/DatabaseServiceProvider.php(24): EvolutionCMS\Database-&gt;__construct(Array, 'AgelxNash\\Modx\\...')
#5 /home/.../core/vendor/illuminate/container/Container.php(799): EvolutionCMS\Providers\DatabaseServiceProvider-&gt;EvolutionCMS\Providers\{closure}(Object(DocumentParser), Array)
#6 /home/.../core/vendor/illuminate/container/Container.php(681): Illuminate\Container\Container-&gt;build(Object(Closure))
#7 /home/.../core/vendor/illuminate/container/Container.php(638): Illuminate\Container\Container-&gt;resolve('DBAPI')
#8 /home/.../core/src/AbstractLaravel.php(586): Illuminate\Container\Container-&gt;get('DBAPI')
#9 /home/.../core/src/AbstractLaravel.php(599): EvolutionCMS\AbstractLaravel-&gt;getService('DBAPI')
#10 /home/.../core/src/ExceptionHandler.php(340): EvolutionCMS\AbstractLaravel-&gt;getDatabase()
#11 /home/.../core/src/ExceptionHandler.php(510): EvolutionCMS\ExceptionHandler-&gt;messageQuit('ReflectionPrope...', '', true, '', '/home/.../w...', 'Parser / Reflec...', '', 62, '', Array)
#12 [internal function]: EvolutionCMS\ExceptionHandler-&gt;handleException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#13 {main}
  thrown in <b>/home/.../core/vendor/agelxnash/modx-evo-database/src/Drivers/IlluminateDriver.php</b> on line <b>62</b><br />
```
The same text in both admin frames and on the frontend

**Comment by sashabeep** [comment]
Switched back to php 7.4 on 2.0.4 and i was able to install from zip and even see the last line
**No Users or Permissions found. Temporary table not needed.**

but again after pressing Run 
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'
```

**Comment by BBloke** [comment]
> @BBloke test site on 2.0.4 completely broken after installation via zip upload or from extras
> 
> ```
> <b>Fatal error</b>:  Uncaught TypeError: ReflectionProperty::getValue(): Argument #1 ($object) must be of type ?object, string given in /home/.../core/vendor/agelxnash/modx-evo-database/src/Drivers/IlluminateDriver.php:62
> Stack trace:
> #0 /home/.../core/vendor/agelxnash/modx-evo-database/src/Drivers/IlluminateDriver.php(62): ReflectionProperty-&gt;getValue('Illuminate\\Data...')
> #1 /home/.../core/vendor/agelxnash/modx-evo-database/src/AbstractDatabase.php(295): AgelxNash\Modx\Evo\Database\Drivers\IlluminateDriver-&gt;__construct(Array)
> #2 /home/.../core/vendor/agelxnash/modx-evo-database/src/Database.php(13): AgelxNash\Modx\Evo\Database\AbstractDatabase-&gt;setDriver('AgelxNash\\Modx\\...')
> #3 /home/.../core/src/Database.php(14): AgelxNash\Modx\Evo\Database\Database-&gt;__construct(Array, 'AgelxNash\\Modx\\...')
> #4 /home/.../core/src/Providers/DatabaseServiceProvider.php(24): EvolutionCMS\Database-&gt;__construct(Array, 'AgelxNash\\Modx\\...')
> #5 /home/.../core/vendor/illuminate/container/Container.php(799): EvolutionCMS\Providers\DatabaseServiceProvider-&gt;EvolutionCMS\Providers\{closure}(Object(DocumentParser), Array)
> #6 /home/.../core/vendor/illuminate/container/Container.php(681): Illuminate\Container\Container-&gt;build(Object(Closure))
> #7 /home/.../core/vendor/illuminate/container/Container.php(638): Illuminate\Container\Container-&gt;resolve('DBAPI')
> #8 /home/.../core/src/AbstractLaravel.php(586): Illuminate\Container\Container-&gt;get('DBAPI')
> #9 /home/.../core/src/AbstractLaravel.php(599): EvolutionCMS\AbstractLaravel-&gt;getService('DBAPI')
> #10 /home/.../core/src/ExceptionHandler.php(340): EvolutionCMS\AbstractLaravel-&gt;getDatabase()
> #11 /home/.../core/src/ExceptionHandler.php(510): EvolutionCMS\ExceptionHandler-&gt;messageQuit('ReflectionPrope...', '', true, '', '/home/.../w...', 'Parser / Reflec...', '', 62, '', Array)
> #12 [internal function]: EvolutionCMS\ExceptionHandler-&gt;handleException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
> #13 {main}
>   thrown in <b>/home/.../core/vendor/agelxnash/modx-evo-database/src/Drivers/IlluminateDriver.php</b> on line <b>62</b><br />
> ```
> 
> The same text in both admin frames and on the frontend

I think this is something outside of the script although during the process of migration.  I hadn't encountered it previously but testing my own site, which worked flawlessly before, doesn't now.

I can see there is the /install folder so v3 has downloaded and extracted.

Curiously, I ran the install process and it completed and the site ended up at v3.

I also tried my v1.0.10 code which ended the same!
